SET IDENTITY_INSERT [AI].[SourceValueOverride] ON 
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (1, N'EmployeeCode', N'63032704', N'2724', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (2, N'EmployeeCode', N'63032709', N'2754', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (3, N'EmployeeCode', N'63032702', N'2780', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (4, N'EmployeeCode', N'63032705', N'2806', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (5, N'EmployeeCode', N'63032802', N'2756', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (6, N'EmployeeCode', N'63032803', N'2755', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (7, N'EmployeeCode', N'63032804', N'2800', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (8, N'EmployeeCode', N'63032807', N'2742', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (9, N'EmployeeCode', N'63032775', N'2677', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (10, N'EmployeeCode', N'63032770', N'2750', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (11, N'EmployeeCode', N'63032777', N'2778', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (12, N'EmployeeCode', N'63033012', N'2758', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (13, N'EmployeeCode', N'63033013', N'2757', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (14, N'EmployeeCode', N'63032582', N'2805', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (15, N'EmployeeCode', N'63032595', N'2790', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (16, N'EmployeeCode', N'63033055', N'2777', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (17, N'EmployeeCode', N'63033056', N'2793', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (18, N'EmployeeCode', N'63033058', N'2761', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (19, N'EmployeeCode', N'63032549', N'2770', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (20, N'EmployeeCode', N'63032606', N'2760', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (21, N'EmployeeCode', N'63032558', N'2808', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (22, N'EmployeeCode', N'63033354', N'2753', NULL, NULL, NULL)
INSERT [AI].[SourceValueOverride] ([OID], [SourceFieldName], [SourceValue], [OverrideValue], [Comment], [OptimisticLockField], [GCRecord]) VALUES (23, N'EmployeeCode', N'63032829', N'2775', NULL, NULL, NULL)
SET IDENTITY_INSERT [AI].[SourceValueOverride] OFF
