IF OBJECT_ID('AI.LeaveBalanceQueueHistory', 'U') IS NOT NULL DROP TABLE AI.LeaveBalanceQueueHistory
CREATE TABLE [AI].[LeaveBalanceQueueHistory](
	[OID] [int] NULL,
	[EventCode] [nvarchar](100) NULL,
	[EventDescription] [nvarchar](100) NULL,
	[EventSequenceID] [smallint] NULL,
	[EffectiveStartDate] [datetime] NULL,
	[EffectiveEndDate] [datetime] NULL,
	[CountryCodeIndicator] [nvarchar](100) NULL,
	[EmployeeCode] [nvarchar](100) NULL,
	[LeaveTypeCode] [nvarchar](100) NULL,
	[LeaveCode] [nvarchar](100) NULL,
	[UnitAdjustment] [nvarchar](100) NULL,
	[UnitOverride] [nvarchar](100) NULL,
	[DateCreated] datetime NULL,
	[LastChanged] datetime NULL,
	[QueueComment] [nvarchar](max) NULL,
	[QueueFilter] [nvarchar](max) NULL,
	[StatusCode] [nvarchar](100) NULL,
	[StatusMessage] [nvarchar](max) NULL,
	[WarningCode] [nvarchar](100) NULL,
	[WarningMessage] [nvarchar](max) NULL,
	[ErrorCode] [nvarchar](100) NULL,
	[ErrorMessage] [nvarchar](max) NULL,
	[OptimisticLockField] [int] NULL,
	[GCRecord] [int] NULL,
)
