IF OBJECT_ID('AI.EmployeeBatchValidations', 'P') IS NOT NULL DROP PROCEDURE AI.EmployeeBatchValidations
IF OBJECT_ID('AI.MappingValidations', 'P') IS NOT NULL DROP PROCEDURE AI.MappingValidations
IF OBJECT_ID('AI.ValidateBatchTemplates', 'P') IS NOT NULL DROP PROCEDURE AI.ValidateBatchTemplates
IF OBJECT_ID('AI.ProcessEmployeeQueue', 'P') IS NOT NULL DROP PROCEDURE AI.ProcessEmployeeQueue
IF OBJECT_ID('AI.FinancialBatchSP', 'P') IS NOT NULL DROP PROCEDURE AI.FinancialBatchSP
IF OBJECT_ID('AI.ProcessFinancialQueue', 'P') IS NOT NULL DROP PROCEDURE AI.ProcessFinancialQueue
IF OBJECT_ID('AI.RefreshValidationWarnings', 'P') IS NOT NULL DROP PROCEDURE AI.RefreshValidationWarnings
IF OBJECT_ID('AI.LeaveTransactionToBalanceQueue', 'P') IS NOT NULL DROP PROCEDURE AI.LeaveTransactionToBalanceQueue
IF OBJECT_ID('AI.ProcessLeaveQueue', 'P') IS NOT NULL DROP PROCEDURE AI.ProcessLeaveQueue
IF OBJECT_ID('AI.AutoCreateHierarchy', 'P') IS NOT NULL DROP PROCEDURE AI.AutoCreateHierarchy
IF OBJECT_ID('AI.LeaveBalanceValidations', 'P') IS NOT NULL DROP PROCEDURE AI.LeaveBalanceValidations
IF OBJECT_ID('AI.RevertUserDefinedBatch', 'P') IS NOT NULL DROP PROCEDURE AI.RevertUserDefinedBatch
IF OBJECT_ID('AI.ArchiveTableData', 'P') IS NOT NULL DROP PROCEDURE AI.ArchiveTableData
IF OBJECT_ID('AI.ClearHistorySystemBatches', 'P') IS NOT NULL DROP PROCEDURE AI.ClearHistorySystemBatches