//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.AbsenceSource")]
    public partial class AIAbsenceSource : XPObject
    {
        string fCountryCodeIndicator;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCodeIndicator
        {
            get { return fCountryCodeIndicator; }
            set { SetPropertyValue<string>(nameof(CountryCodeIndicator), ref fCountryCodeIndicator, value); }
        }
        string fEmployeeCode;
        [Size(SizeAttribute.Unlimited)]
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fLeaveID;
        [Size(SizeAttribute.Unlimited)]
        public string LeaveID
        {
            get { return fLeaveID; }
            set { SetPropertyValue<string>(nameof(LeaveID), ref fLeaveID, value); }
        }
        string fLeaveTypeID;
        [Size(SizeAttribute.Unlimited)]
        public string LeaveTypeID
        {
            get { return fLeaveTypeID; }
            set { SetPropertyValue<string>(nameof(LeaveTypeID), ref fLeaveTypeID, value); }
        }
        string fLeaveAction;
        [Size(SizeAttribute.Unlimited)]
        public string LeaveAction
        {
            get { return fLeaveAction; }
            set { SetPropertyValue<string>(nameof(LeaveAction), ref fLeaveAction, value); }
        }
        DateTime fFromDate;
        public DateTime FromDate
        {
            get { return fFromDate; }
            set { SetPropertyValue<DateTime>(nameof(FromDate), ref fFromDate, value); }
        }
        DateTime fToDate;
        public DateTime ToDate
        {
            get { return fToDate; }
            set { SetPropertyValue<DateTime>(nameof(ToDate), ref fToDate, value); }
        }
        string fUnitsTaken;
        [Size(SizeAttribute.Unlimited)]
        public string UnitsTaken
        {
            get { return fUnitsTaken; }
            set { SetPropertyValue<string>(nameof(UnitsTaken), ref fUnitsTaken, value); }
        }
        string fUnit;
        [Size(SizeAttribute.Unlimited)]
        public string Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<string>(nameof(Unit), ref fUnit, value); }
        }
        string fSourceFileName;
        [Size(SizeAttribute.Unlimited)]
        public string SourceFileName
        {
            get { return fSourceFileName; }
            set { SetPropertyValue<string>(nameof(SourceFileName), ref fSourceFileName, value); }
        }
    }

}
