//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.AllowanceAndOTPSource")]
    public partial class AIAllowanceAndOTPSource : XPObject
    {
        string fCountryCodeIndicator;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCodeIndicator
        {
            get { return fCountryCodeIndicator; }
            set { SetPropertyValue<string>(nameof(CountryCodeIndicator), ref fCountryCodeIndicator, value); }
        }
        string fEmployeeCode;
        [Size(SizeAttribute.Unlimited)]
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fWageTypeCode;
        [Size(SizeAttribute.Unlimited)]
        public string WageTypeCode
        {
            get { return fWageTypeCode; }
            set { SetPropertyValue<string>(nameof(WageTypeCode), ref fWageTypeCode, value); }
        }
        string fAmount;
        [Size(SizeAttribute.Unlimited)]
        public string Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<string>(nameof(Amount), ref fAmount, value); }
        }
        string fCcy;
        [Size(SizeAttribute.Unlimited)]
        public string Ccy
        {
            get { return fCcy; }
            set { SetPropertyValue<string>(nameof(Ccy), ref fCcy, value); }
        }
        string fOneTimePayment;
        [Size(SizeAttribute.Unlimited)]
        public string OneTimePayment
        {
            get { return fOneTimePayment; }
            set { SetPropertyValue<string>(nameof(OneTimePayment), ref fOneTimePayment, value); }
        }
        string fFrequency;
        [Size(SizeAttribute.Unlimited)]
        public string Frequency
        {
            get { return fFrequency; }
            set { SetPropertyValue<string>(nameof(Frequency), ref fFrequency, value); }
        }
        DateTime fEffectiveDate;
        public DateTime EffectiveDate
        {
            get { return fEffectiveDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveDate), ref fEffectiveDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value); }
        }
        string fSourceFileName;
        [Size(SizeAttribute.Unlimited)]
        public string SourceFileName
        {
            get { return fSourceFileName; }
            set { SetPropertyValue<string>(nameof(SourceFileName), ref fSourceFileName, value); }
        }
    }

}
