//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.EmployeeSubQueue")]
    public partial class AIEmployeeSubQueue : XPObject
    {
        int fEmployeeQueueOID;
        public int EmployeeQueueOID
        {
            get { return fEmployeeQueueOID; }
            set { SetPropertyValue<int>(nameof(EmployeeQueueOID), ref fEmployeeQueueOID, value); }
        }
        string fEmployeeCode;
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fSubQueueTableType;
        public string SubQueueTableType
        {
            get { return fSubQueueTableType; }
            set { SetPropertyValue<string>(nameof(SubQueueTableType), ref fSubQueueTableType, value); }
        }
        string fSubQueueType;
        [Size(SizeAttribute.Unlimited)]
        public string SubQueueType
        {
            get { return fSubQueueType; }
            set { SetPropertyValue<string>(nameof(SubQueueType), ref fSubQueueType, value); }
        }
        string fSubQueueValue;
        [Size(SizeAttribute.Unlimited)]
        public string SubQueueValue
        {
            get { return fSubQueueValue; }
            set { SetPropertyValue<string>(nameof(SubQueueValue), ref fSubQueueValue, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fLastChanged;
        public DateTime LastChanged
        {
            get { return fLastChanged; }
            set { SetPropertyValue<DateTime>(nameof(LastChanged), ref fLastChanged, value); }
        }
        string fQueueComment;
        public string QueueComment
        {
            get { return fQueueComment; }
            set { SetPropertyValue<string>(nameof(QueueComment), ref fQueueComment, value); }
        }
        string fQueueFilter;
        public string QueueFilter
        {
            get { return fQueueFilter; }
            set { SetPropertyValue<string>(nameof(QueueFilter), ref fQueueFilter, value); }
        }
    }

}
