//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.EmployeeSource")]
    public partial class AIEmployeeSource : XPObject
    {
        string fCountryCodeIndicator;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCodeIndicator
        {
            get { return fCountryCodeIndicator; }
            set { SetPropertyValue<string>(nameof(CountryCodeIndicator), ref fCountryCodeIndicator, value); }
        }
        string fEmployeeCode;
        [Size(SizeAttribute.Unlimited)]
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fCompanyID;
        [Size(SizeAttribute.Unlimited)]
        public string CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<string>(nameof(CompanyID), ref fCompanyID, value); }
        }
        string fTaxNo;
        [Size(SizeAttribute.Unlimited)]
        public string TaxNo
        {
            get { return fTaxNo; }
            set { SetPropertyValue<string>(nameof(TaxNo), ref fTaxNo, value); }
        }
        string fTitleTypeID;
        [Size(SizeAttribute.Unlimited)]
        public string TitleTypeID
        {
            get { return fTitleTypeID; }
            set { SetPropertyValue<string>(nameof(TitleTypeID), ref fTitleTypeID, value); }
        }
        string fFirstName;
        [Size(SizeAttribute.Unlimited)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fSecondName;
        [Size(SizeAttribute.Unlimited)]
        public string SecondName
        {
            get { return fSecondName; }
            set { SetPropertyValue<string>(nameof(SecondName), ref fSecondName, value); }
        }
        string fKnownAsName;
        [Size(SizeAttribute.Unlimited)]
        public string KnownAsName
        {
            get { return fKnownAsName; }
            set { SetPropertyValue<string>(nameof(KnownAsName), ref fKnownAsName, value); }
        }
        string fLastName;
        [Size(SizeAttribute.Unlimited)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fMaritalStatusTypeID;
        [Size(SizeAttribute.Unlimited)]
        public string MaritalStatusTypeID
        {
            get { return fMaritalStatusTypeID; }
            set { SetPropertyValue<string>(nameof(MaritalStatusTypeID), ref fMaritalStatusTypeID, value); }
        }
        string fIDNumber;
        [Size(SizeAttribute.Unlimited)]
        public string IDNumber
        {
            get { return fIDNumber; }
            set { SetPropertyValue<string>(nameof(IDNumber), ref fIDNumber, value); }
        }
        string fIDNumberExpiryDate;
        [Size(SizeAttribute.Unlimited)]
        public string IDNumberExpiryDate
        {
            get { return fIDNumberExpiryDate; }
            set { SetPropertyValue<string>(nameof(IDNumberExpiryDate), ref fIDNumberExpiryDate, value); }
        }
        string fBirthDate;
        [Size(SizeAttribute.Unlimited)]
        public string BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<string>(nameof(BirthDate), ref fBirthDate, value); }
        }
        string fCityOfBirth;
        [Size(SizeAttribute.Unlimited)]
        public string CityOfBirth
        {
            get { return fCityOfBirth; }
            set { SetPropertyValue<string>(nameof(CityOfBirth), ref fCityOfBirth, value); }
        }
        string fGender;
        [Size(SizeAttribute.Unlimited)]
        public string Gender
        {
            get { return fGender; }
            set { SetPropertyValue<string>(nameof(Gender), ref fGender, value); }
        }
        string fNationalityCountryCode;
        [Size(SizeAttribute.Unlimited)]
        public string NationalityCountryCode
        {
            get { return fNationalityCountryCode; }
            set { SetPropertyValue<string>(nameof(NationalityCountryCode), ref fNationalityCountryCode, value); }
        }
        string fCountryOfBirth;
        [Size(SizeAttribute.Unlimited)]
        public string CountryOfBirth
        {
            get { return fCountryOfBirth; }
            set { SetPropertyValue<string>(nameof(CountryOfBirth), ref fCountryOfBirth, value); }
        }
        string fPassportNo;
        [Size(SizeAttribute.Unlimited)]
        public string PassportNo
        {
            get { return fPassportNo; }
            set { SetPropertyValue<string>(nameof(PassportNo), ref fPassportNo, value); }
        }
        string fPassportCountryCode;
        [Size(SizeAttribute.Unlimited)]
        public string PassportCountryCode
        {
            get { return fPassportCountryCode; }
            set { SetPropertyValue<string>(nameof(PassportCountryCode), ref fPassportCountryCode, value); }
        }
        string fDisabled;
        [Size(SizeAttribute.Unlimited)]
        public string Disabled
        {
            get { return fDisabled; }
            set { SetPropertyValue<string>(nameof(Disabled), ref fDisabled, value); }
        }
        string fRacialGroup;
        [Size(SizeAttribute.Unlimited)]
        public string RacialGroup
        {
            get { return fRacialGroup; }
            set { SetPropertyValue<string>(nameof(RacialGroup), ref fRacialGroup, value); }
        }
        string fDateEngaged;
        [Size(SizeAttribute.Unlimited)]
        public string DateEngaged
        {
            get { return fDateEngaged; }
            set { SetPropertyValue<string>(nameof(DateEngaged), ref fDateEngaged, value); }
        }
        string fTerminationDate;
        [Size(SizeAttribute.Unlimited)]
        public string TerminationDate
        {
            get { return fTerminationDate; }
            set { SetPropertyValue<string>(nameof(TerminationDate), ref fTerminationDate, value); }
        }
        string fTerminationReasonID;
        [Size(SizeAttribute.Unlimited)]
        public string TerminationReasonID
        {
            get { return fTerminationReasonID; }
            set { SetPropertyValue<string>(nameof(TerminationReasonID), ref fTerminationReasonID, value); }
        }
        string fDateJoinedGroup;
        [Size(SizeAttribute.Unlimited)]
        public string DateJoinedGroup
        {
            get { return fDateJoinedGroup; }
            set { SetPropertyValue<string>(nameof(DateJoinedGroup), ref fDateJoinedGroup, value); }
        }
        string fLeaveStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string LeaveStartDate
        {
            get { return fLeaveStartDate; }
            set { SetPropertyValue<string>(nameof(LeaveStartDate), ref fLeaveStartDate, value); }
        }
        string fProbationPeriodEndDate;
        [Size(SizeAttribute.Unlimited)]
        public string ProbationPeriodEndDate
        {
            get { return fProbationPeriodEndDate; }
            set { SetPropertyValue<string>(nameof(ProbationPeriodEndDate), ref fProbationPeriodEndDate, value); }
        }
        string fAnnualSalary;
        [Size(SizeAttribute.Unlimited)]
        public string AnnualSalary
        {
            get { return fAnnualSalary; }
            set { SetPropertyValue<string>(nameof(AnnualSalary), ref fAnnualSalary, value); }
        }
        string fPeriodSalary;
        [Size(SizeAttribute.Unlimited)]
        public string PeriodSalary
        {
            get { return fPeriodSalary; }
            set { SetPropertyValue<string>(nameof(PeriodSalary), ref fPeriodSalary, value); }
        }
        string fRatePerHour;
        [Size(SizeAttribute.Unlimited)]
        public string RatePerHour
        {
            get { return fRatePerHour; }
            set { SetPropertyValue<string>(nameof(RatePerHour), ref fRatePerHour, value); }
        }
        string fPensionFundStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string PensionFundStartDate
        {
            get { return fPensionFundStartDate; }
            set { SetPropertyValue<string>(nameof(PensionFundStartDate), ref fPensionFundStartDate, value); }
        }
        string fProvidentFundStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string ProvidentFundStartDate
        {
            get { return fProvidentFundStartDate; }
            set { SetPropertyValue<string>(nameof(ProvidentFundStartDate), ref fProvidentFundStartDate, value); }
        }
        string fMedicalStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string MedicalStartDate
        {
            get { return fMedicalStartDate; }
            set { SetPropertyValue<string>(nameof(MedicalStartDate), ref fMedicalStartDate, value); }
        }
        string fForeignIncome;
        [Size(SizeAttribute.Unlimited)]
        public string ForeignIncome
        {
            get { return fForeignIncome; }
            set { SetPropertyValue<string>(nameof(ForeignIncome), ref fForeignIncome, value); }
        }
        string fTaxStartDate;
        [Size(SizeAttribute.Unlimited)]
        public string TaxStartDate
        {
            get { return fTaxStartDate; }
            set { SetPropertyValue<string>(nameof(TaxStartDate), ref fTaxStartDate, value); }
        }
        string fUseWork;
        [Size(SizeAttribute.Unlimited)]
        public string UseWork
        {
            get { return fUseWork; }
            set { SetPropertyValue<string>(nameof(UseWork), ref fUseWork, value); }
        }
        string fUnitPostalNumber;
        [Size(SizeAttribute.Unlimited)]
        public string UnitPostalNumber
        {
            get { return fUnitPostalNumber; }
            set { SetPropertyValue<string>(nameof(UnitPostalNumber), ref fUnitPostalNumber, value); }
        }
        string fComplex;
        [Size(SizeAttribute.Unlimited)]
        public string Complex
        {
            get { return fComplex; }
            set { SetPropertyValue<string>(nameof(Complex), ref fComplex, value); }
        }
        string fStreetNumber;
        [Size(SizeAttribute.Unlimited)]
        public string StreetNumber
        {
            get { return fStreetNumber; }
            set { SetPropertyValue<string>(nameof(StreetNumber), ref fStreetNumber, value); }
        }
        string fStreetFarmName;
        [Size(SizeAttribute.Unlimited)]
        public string StreetFarmName
        {
            get { return fStreetFarmName; }
            set { SetPropertyValue<string>(nameof(StreetFarmName), ref fStreetFarmName, value); }
        }
        string fSuburbDistrict;
        [Size(SizeAttribute.Unlimited)]
        public string SuburbDistrict
        {
            get { return fSuburbDistrict; }
            set { SetPropertyValue<string>(nameof(SuburbDistrict), ref fSuburbDistrict, value); }
        }
        string fCityTown;
        [Size(SizeAttribute.Unlimited)]
        public string CityTown
        {
            get { return fCityTown; }
            set { SetPropertyValue<string>(nameof(CityTown), ref fCityTown, value); }
        }
        string fProvince;
        [Size(SizeAttribute.Unlimited)]
        public string Province
        {
            get { return fProvince; }
            set { SetPropertyValue<string>(nameof(Province), ref fProvince, value); }
        }
        string fPostalCode;
        [Size(SizeAttribute.Unlimited)]
        public string PostalCode
        {
            get { return fPostalCode; }
            set { SetPropertyValue<string>(nameof(PostalCode), ref fPostalCode, value); }
        }
        string fCountryCode;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCode
        {
            get { return fCountryCode; }
            set { SetPropertyValue<string>(nameof(CountryCode), ref fCountryCode, value); }
        }
        string fUsePhysical1;
        [Size(SizeAttribute.Unlimited)]
        public string UsePhysical1
        {
            get { return fUsePhysical1; }
            set { SetPropertyValue<string>(nameof(UsePhysical1), ref fUsePhysical1, value); }
        }
        string fUnitPostalNumber1;
        [Size(SizeAttribute.Unlimited)]
        public string UnitPostalNumber1
        {
            get { return fUnitPostalNumber1; }
            set { SetPropertyValue<string>(nameof(UnitPostalNumber1), ref fUnitPostalNumber1, value); }
        }
        string fComplex1;
        [Size(SizeAttribute.Unlimited)]
        public string Complex1
        {
            get { return fComplex1; }
            set { SetPropertyValue<string>(nameof(Complex1), ref fComplex1, value); }
        }
        string fStreetNumber1;
        [Size(SizeAttribute.Unlimited)]
        public string StreetNumber1
        {
            get { return fStreetNumber1; }
            set { SetPropertyValue<string>(nameof(StreetNumber1), ref fStreetNumber1, value); }
        }
        string fStreetFarmName1;
        [Size(SizeAttribute.Unlimited)]
        public string StreetFarmName1
        {
            get { return fStreetFarmName1; }
            set { SetPropertyValue<string>(nameof(StreetFarmName1), ref fStreetFarmName1, value); }
        }
        string fSuburbDistrict1;
        [Size(SizeAttribute.Unlimited)]
        public string SuburbDistrict1
        {
            get { return fSuburbDistrict1; }
            set { SetPropertyValue<string>(nameof(SuburbDistrict1), ref fSuburbDistrict1, value); }
        }
        string fCityTown1;
        [Size(SizeAttribute.Unlimited)]
        public string CityTown1
        {
            get { return fCityTown1; }
            set { SetPropertyValue<string>(nameof(CityTown1), ref fCityTown1, value); }
        }
        string fProvince1;
        [Size(SizeAttribute.Unlimited)]
        public string Province1
        {
            get { return fProvince1; }
            set { SetPropertyValue<string>(nameof(Province1), ref fProvince1, value); }
        }
        string fPostalCode1;
        [Size(SizeAttribute.Unlimited)]
        public string PostalCode1
        {
            get { return fPostalCode1; }
            set { SetPropertyValue<string>(nameof(PostalCode1), ref fPostalCode1, value); }
        }
        string fCountryCode1;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCode1
        {
            get { return fCountryCode1; }
            set { SetPropertyValue<string>(nameof(CountryCode1), ref fCountryCode1, value); }
        }
        string fUsePostal2;
        [Size(SizeAttribute.Unlimited)]
        public string UsePostal2
        {
            get { return fUsePostal2; }
            set { SetPropertyValue<string>(nameof(UsePostal2), ref fUsePostal2, value); }
        }
        string fUnitPostalNumber2;
        [Size(SizeAttribute.Unlimited)]
        public string UnitPostalNumber2
        {
            get { return fUnitPostalNumber2; }
            set { SetPropertyValue<string>(nameof(UnitPostalNumber2), ref fUnitPostalNumber2, value); }
        }
        string fComplex2;
        [Size(SizeAttribute.Unlimited)]
        public string Complex2
        {
            get { return fComplex2; }
            set { SetPropertyValue<string>(nameof(Complex2), ref fComplex2, value); }
        }
        string fStreetNumber2;
        [Size(SizeAttribute.Unlimited)]
        public string StreetNumber2
        {
            get { return fStreetNumber2; }
            set { SetPropertyValue<string>(nameof(StreetNumber2), ref fStreetNumber2, value); }
        }
        string fStreetFarmName2;
        [Size(SizeAttribute.Unlimited)]
        public string StreetFarmName2
        {
            get { return fStreetFarmName2; }
            set { SetPropertyValue<string>(nameof(StreetFarmName2), ref fStreetFarmName2, value); }
        }
        string fSuburbDistrict2;
        [Size(SizeAttribute.Unlimited)]
        public string SuburbDistrict2
        {
            get { return fSuburbDistrict2; }
            set { SetPropertyValue<string>(nameof(SuburbDistrict2), ref fSuburbDistrict2, value); }
        }
        string fCityTown2;
        [Size(SizeAttribute.Unlimited)]
        public string CityTown2
        {
            get { return fCityTown2; }
            set { SetPropertyValue<string>(nameof(CityTown2), ref fCityTown2, value); }
        }
        string fProvince2;
        [Size(SizeAttribute.Unlimited)]
        public string Province2
        {
            get { return fProvince2; }
            set { SetPropertyValue<string>(nameof(Province2), ref fProvince2, value); }
        }
        string fPostalCode2;
        [Size(SizeAttribute.Unlimited)]
        public string PostalCode2
        {
            get { return fPostalCode2; }
            set { SetPropertyValue<string>(nameof(PostalCode2), ref fPostalCode2, value); }
        }
        string fCountryCode2;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCode2
        {
            get { return fCountryCode2; }
            set { SetPropertyValue<string>(nameof(CountryCode2), ref fCountryCode2, value); }
        }
        string fAccountName;
        [Size(SizeAttribute.Unlimited)]
        public string AccountName
        {
            get { return fAccountName; }
            set { SetPropertyValue<string>(nameof(AccountName), ref fAccountName, value); }
        }
        string fAccountTypeID;
        [Size(SizeAttribute.Unlimited)]
        public string AccountTypeID
        {
            get { return fAccountTypeID; }
            set { SetPropertyValue<string>(nameof(AccountTypeID), ref fAccountTypeID, value); }
        }
        string fAccountNo;
        [Size(SizeAttribute.Unlimited)]
        public string AccountNo
        {
            get { return fAccountNo; }
            set { SetPropertyValue<string>(nameof(AccountNo), ref fAccountNo, value); }
        }
        string fBankBranchID;
        [Size(SizeAttribute.Unlimited)]
        public string BankBranchID
        {
            get { return fBankBranchID; }
            set { SetPropertyValue<string>(nameof(BankBranchID), ref fBankBranchID, value); }
        }
        string fCcy;
        [Size(SizeAttribute.Unlimited)]
        public string Ccy
        {
            get { return fCcy; }
            set { SetPropertyValue<string>(nameof(Ccy), ref fCcy, value); }
        }
        string fHome;
        [Size(SizeAttribute.Unlimited)]
        public string Home
        {
            get { return fHome; }
            set { SetPropertyValue<string>(nameof(Home), ref fHome, value); }
        }
        string fWork;
        [Size(SizeAttribute.Unlimited)]
        public string Work
        {
            get { return fWork; }
            set { SetPropertyValue<string>(nameof(Work), ref fWork, value); }
        }
        string fFax;
        [Size(SizeAttribute.Unlimited)]
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>(nameof(Fax), ref fFax, value); }
        }
        string fCell;
        [Size(SizeAttribute.Unlimited)]
        public string Cell
        {
            get { return fCell; }
            set { SetPropertyValue<string>(nameof(Cell), ref fCell, value); }
        }
        string fMail;
        [Size(SizeAttribute.Unlimited)]
        public string Mail
        {
            get { return fMail; }
            set { SetPropertyValue<string>(nameof(Mail), ref fMail, value); }
        }
        string fPaypoint;
        [Size(SizeAttribute.Unlimited)]
        public string Paypoint
        {
            get { return fPaypoint; }
            set { SetPropertyValue<string>(nameof(Paypoint), ref fPaypoint, value); }
        }
        string fRSCCode;
        [Size(SizeAttribute.Unlimited)]
        public string RSCCode
        {
            get { return fRSCCode; }
            set { SetPropertyValue<string>(nameof(RSCCode), ref fRSCCode, value); }
        }
        string fSocialSecurityNumber;
        [Size(SizeAttribute.Unlimited)]
        public string SocialSecurityNumber
        {
            get { return fSocialSecurityNumber; }
            set { SetPropertyValue<string>(nameof(SocialSecurityNumber), ref fSocialSecurityNumber, value); }
        }
        string fNHIFNumber;
        [Size(SizeAttribute.Unlimited)]
        public string NHIFNumber
        {
            get { return fNHIFNumber; }
            set { SetPropertyValue<string>(nameof(NHIFNumber), ref fNHIFNumber, value); }
        }
        string fNSSFNumber;
        [Size(SizeAttribute.Unlimited)]
        public string NSSFNumber
        {
            get { return fNSSFNumber; }
            set { SetPropertyValue<string>(nameof(NSSFNumber), ref fNSSFNumber, value); }
        }
        string fNSSFMembershipNumber;
        [Size(SizeAttribute.Unlimited)]
        public string NSSFMembershipNumber
        {
            get { return fNSSFMembershipNumber; }
            set { SetPropertyValue<string>(nameof(NSSFMembershipNumber), ref fNSSFMembershipNumber, value); }
        }
        string fPPFMembershipNumber;
        [Size(SizeAttribute.Unlimited)]
        public string PPFMembershipNumber
        {
            get { return fPPFMembershipNumber; }
            set { SetPropertyValue<string>(nameof(PPFMembershipNumber), ref fPPFMembershipNumber, value); }
        }
        string fSourceFileName;
        [Size(SizeAttribute.Unlimited)]
        public string SourceFileName
        {
            get { return fSourceFileName; }
            set { SetPropertyValue<string>(nameof(SourceFileName), ref fSourceFileName, value); }
        }
    }

}
