//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.EmployeeQueue")]
    public partial class AIEmployeeQueue : XPObject
    {
        string fEventCode;
        public string EventCode
        {
            get { return fEventCode; }
            set { SetPropertyValue<string>(nameof(EventCode), ref fEventCode, value); }
        }
        string fEventDescription;
        public string EventDescription
        {
            get { return fEventDescription; }
            set { SetPropertyValue<string>(nameof(EventDescription), ref fEventDescription, value); }
        }
        short fEventSequenceID;
        public short EventSequenceID
        {
            get { return fEventSequenceID; }
            set { SetPropertyValue<short>(nameof(EventSequenceID), ref fEventSequenceID, value); }
        }
        DateTime fEffectiveStartDate;
        public DateTime EffectiveStartDate
        {
            get { return fEffectiveStartDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveStartDate), ref fEffectiveStartDate, value); }
        }
        DateTime fEffectiveEndDate;
        public DateTime EffectiveEndDate
        {
            get { return fEffectiveEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveEndDate), ref fEffectiveEndDate, value); }
        }
        string fEmployeeCode;
        [DbType("varchar(15)")]
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fEntityCode;
        [DbType("varchar(15)")]
        public string EntityCode
        {
            get { return fEntityCode; }
            set { SetPropertyValue<string>(nameof(EntityCode), ref fEntityCode, value); }
        }
        string fCompanyCode;
        public string CompanyCode
        {
            get { return fCompanyCode; }
            set { SetPropertyValue<string>(nameof(CompanyCode), ref fCompanyCode, value); }
        }
        string fCompanyRuleCode;
        public string CompanyRuleCode
        {
            get { return fCompanyRuleCode; }
            set { SetPropertyValue<string>(nameof(CompanyRuleCode), ref fCompanyRuleCode, value); }
        }
        string fPaymentRunDefCode;
        public string PaymentRunDefCode
        {
            get { return fPaymentRunDefCode; }
            set { SetPropertyValue<string>(nameof(PaymentRunDefCode), ref fPaymentRunDefCode, value); }
        }
        string fRemunerationEarnDefCode;
        public string RemunerationEarnDefCode
        {
            get { return fRemunerationEarnDefCode; }
            set { SetPropertyValue<string>(nameof(RemunerationEarnDefCode), ref fRemunerationEarnDefCode, value); }
        }
        string fLeavePolicyCode;
        public string LeavePolicyCode
        {
            get { return fLeavePolicyCode; }
            set { SetPropertyValue<string>(nameof(LeavePolicyCode), ref fLeavePolicyCode, value); }
        }
        string fGenEntityTypeCode;
        public string GenEntityTypeCode
        {
            get { return fGenEntityTypeCode; }
            set { SetPropertyValue<string>(nameof(GenEntityTypeCode), ref fGenEntityTypeCode, value); }
        }
        string fGenEntitySubTypeCode;
        public string GenEntitySubTypeCode
        {
            get { return fGenEntitySubTypeCode; }
            set { SetPropertyValue<string>(nameof(GenEntitySubTypeCode), ref fGenEntitySubTypeCode, value); }
        }
        string fTaxNo;
        public string TaxNo
        {
            get { return fTaxNo; }
            set { SetPropertyValue<string>(nameof(TaxNo), ref fTaxNo, value); }
        }
        string fTitleTypeCode;
        public string TitleTypeCode
        {
            get { return fTitleTypeCode; }
            set { SetPropertyValue<string>(nameof(TitleTypeCode), ref fTitleTypeCode, value); }
        }
        string fInitials;
        public string Initials
        {
            get { return fInitials; }
            set { SetPropertyValue<string>(nameof(Initials), ref fInitials, value); }
        }
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fSecondName;
        public string SecondName
        {
            get { return fSecondName; }
            set { SetPropertyValue<string>(nameof(SecondName), ref fSecondName, value); }
        }
        string fOtherNames;
        public string OtherNames
        {
            get { return fOtherNames; }
            set { SetPropertyValue<string>(nameof(OtherNames), ref fOtherNames, value); }
        }
        string fKnownAsName;
        public string KnownAsName
        {
            get { return fKnownAsName; }
            set { SetPropertyValue<string>(nameof(KnownAsName), ref fKnownAsName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fMaidenName;
        public string MaidenName
        {
            get { return fMaidenName; }
            set { SetPropertyValue<string>(nameof(MaidenName), ref fMaidenName, value); }
        }
        string fArabicFullName;
        public string ArabicFullName
        {
            get { return fArabicFullName; }
            set { SetPropertyValue<string>(nameof(ArabicFullName), ref fArabicFullName, value); }
        }
        string fMaritalStatusTypeCode;
        public string MaritalStatusTypeCode
        {
            get { return fMaritalStatusTypeCode; }
            set { SetPropertyValue<string>(nameof(MaritalStatusTypeCode), ref fMaritalStatusTypeCode, value); }
        }
        string fIdentityTypeCode;
        public string IdentityTypeCode
        {
            get { return fIdentityTypeCode; }
            set { SetPropertyValue<string>(nameof(IdentityTypeCode), ref fIdentityTypeCode, value); }
        }
        string fIDNumber;
        public string IDNumber
        {
            get { return fIDNumber; }
            set { SetPropertyValue<string>(nameof(IDNumber), ref fIDNumber, value); }
        }
        DateTime fIDNumberExpiryDate;
        public DateTime IDNumberExpiryDate
        {
            get { return fIDNumberExpiryDate; }
            set { SetPropertyValue<DateTime>(nameof(IDNumberExpiryDate), ref fIDNumberExpiryDate, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value); }
        }
        string fBirthCertificateNumber;
        public string BirthCertificateNumber
        {
            get { return fBirthCertificateNumber; }
            set { SetPropertyValue<string>(nameof(BirthCertificateNumber), ref fBirthCertificateNumber, value); }
        }
        string fCityOfBirth;
        public string CityOfBirth
        {
            get { return fCityOfBirth; }
            set { SetPropertyValue<string>(nameof(CityOfBirth), ref fCityOfBirth, value); }
        }
        string fGender;
        public string Gender
        {
            get { return fGender; }
            set { SetPropertyValue<string>(nameof(Gender), ref fGender, value); }
        }
        string fLanguageTypeCode;
        public string LanguageTypeCode
        {
            get { return fLanguageTypeCode; }
            set { SetPropertyValue<string>(nameof(LanguageTypeCode), ref fLanguageTypeCode, value); }
        }
        string fNationalityCountryCode;
        public string NationalityCountryCode
        {
            get { return fNationalityCountryCode; }
            set { SetPropertyValue<string>(nameof(NationalityCountryCode), ref fNationalityCountryCode, value); }
        }
        string fCountryOfBirth;
        public string CountryOfBirth
        {
            get { return fCountryOfBirth; }
            set { SetPropertyValue<string>(nameof(CountryOfBirth), ref fCountryOfBirth, value); }
        }
        string fPassportNo;
        public string PassportNo
        {
            get { return fPassportNo; }
            set { SetPropertyValue<string>(nameof(PassportNo), ref fPassportNo, value); }
        }
        string fPassportCountryCode;
        public string PassportCountryCode
        {
            get { return fPassportCountryCode; }
            set { SetPropertyValue<string>(nameof(PassportCountryCode), ref fPassportCountryCode, value); }
        }
        string fDisabled;
        public string Disabled
        {
            get { return fDisabled; }
            set { SetPropertyValue<string>(nameof(Disabled), ref fDisabled, value); }
        }
        string fDisabilityTypeCode;
        public string DisabilityTypeCode
        {
            get { return fDisabilityTypeCode; }
            set { SetPropertyValue<string>(nameof(DisabilityTypeCode), ref fDisabilityTypeCode, value); }
        }
        string fEthnicTypeCode;
        public string EthnicTypeCode
        {
            get { return fEthnicTypeCode; }
            set { SetPropertyValue<string>(nameof(EthnicTypeCode), ref fEthnicTypeCode, value); }
        }
        string fRacialGroup;
        public string RacialGroup
        {
            get { return fRacialGroup; }
            set { SetPropertyValue<string>(nameof(RacialGroup), ref fRacialGroup, value); }
        }
        string fRaceGroupCode;
        public string RaceGroupCode
        {
            get { return fRaceGroupCode; }
            set { SetPropertyValue<string>(nameof(RaceGroupCode), ref fRaceGroupCode, value); }
        }
        string fReligionCode;
        public string ReligionCode
        {
            get { return fReligionCode; }
            set { SetPropertyValue<string>(nameof(ReligionCode), ref fReligionCode, value); }
        }
        string fBloodGroup;
        public string BloodGroup
        {
            get { return fBloodGroup; }
            set { SetPropertyValue<string>(nameof(BloodGroup), ref fBloodGroup, value); }
        }
        DateTime fDateEngaged;
        public DateTime DateEngaged
        {
            get { return fDateEngaged; }
            set { SetPropertyValue<DateTime>(nameof(DateEngaged), ref fDateEngaged, value); }
        }
        string fTaxBranchCode;
        public string TaxBranchCode
        {
            get { return fTaxBranchCode; }
            set { SetPropertyValue<string>(nameof(TaxBranchCode), ref fTaxBranchCode, value); }
        }
        string fUIFStatusCode;
        public string UIFStatusCode
        {
            get { return fUIFStatusCode; }
            set { SetPropertyValue<string>(nameof(UIFStatusCode), ref fUIFStatusCode, value); }
        }
        DateTime fUIFStartDate;
        public DateTime UIFStartDate
        {
            get { return fUIFStartDate; }
            set { SetPropertyValue<DateTime>(nameof(UIFStartDate), ref fUIFStartDate, value); }
        }
        string fJobTitleTypeCode;
        public string JobTitleTypeCode
        {
            get { return fJobTitleTypeCode; }
            set { SetPropertyValue<string>(nameof(JobTitleTypeCode), ref fJobTitleTypeCode, value); }
        }
        string fJobTitleTypeDescription;
        public string JobTitleTypeDescription
        {
            get { return fJobTitleTypeDescription; }
            set { SetPropertyValue<string>(nameof(JobTitleTypeDescription), ref fJobTitleTypeDescription, value); }
        }
        string fJobGradeCode;
        public string JobGradeCode
        {
            get { return fJobGradeCode; }
            set { SetPropertyValue<string>(nameof(JobGradeCode), ref fJobGradeCode, value); }
        }
        string fJobGradeDescription;
        public string JobGradeDescription
        {
            get { return fJobGradeDescription; }
            set { SetPropertyValue<string>(nameof(JobGradeDescription), ref fJobGradeDescription, value); }
        }
        DateTime fTerminationDate;
        public DateTime TerminationDate
        {
            get { return fTerminationDate; }
            set { SetPropertyValue<DateTime>(nameof(TerminationDate), ref fTerminationDate, value); }
        }
        string fTerminationReasonCode;
        public string TerminationReasonCode
        {
            get { return fTerminationReasonCode; }
            set { SetPropertyValue<string>(nameof(TerminationReasonCode), ref fTerminationReasonCode, value); }
        }
        string fFinalCalcNow;
        public string FinalCalcNow
        {
            get { return fFinalCalcNow; }
            set { SetPropertyValue<string>(nameof(FinalCalcNow), ref fFinalCalcNow, value); }
        }
        DateTime fDateJoinedGroup;
        public DateTime DateJoinedGroup
        {
            get { return fDateJoinedGroup; }
            set { SetPropertyValue<DateTime>(nameof(DateJoinedGroup), ref fDateJoinedGroup, value); }
        }
        DateTime fLeaveStartDate;
        public DateTime LeaveStartDate
        {
            get { return fLeaveStartDate; }
            set { SetPropertyValue<DateTime>(nameof(LeaveStartDate), ref fLeaveStartDate, value); }
        }
        string fNatureOfContractCode;
        public string NatureOfContractCode
        {
            get { return fNatureOfContractCode; }
            set { SetPropertyValue<string>(nameof(NatureOfContractCode), ref fNatureOfContractCode, value); }
        }
        DateTime fProbationPeriodEndDate;
        public DateTime ProbationPeriodEndDate
        {
            get { return fProbationPeriodEndDate; }
            set { SetPropertyValue<DateTime>(nameof(ProbationPeriodEndDate), ref fProbationPeriodEndDate, value); }
        }
        string fHoursPerPeriod;
        public string HoursPerPeriod
        {
            get { return fHoursPerPeriod; }
            set { SetPropertyValue<string>(nameof(HoursPerPeriod), ref fHoursPerPeriod, value); }
        }
        string fHoursPerDay;
        public string HoursPerDay
        {
            get { return fHoursPerDay; }
            set { SetPropertyValue<string>(nameof(HoursPerDay), ref fHoursPerDay, value); }
        }
        string fAnnualSalary;
        public string AnnualSalary
        {
            get { return fAnnualSalary; }
            set { SetPropertyValue<string>(nameof(AnnualSalary), ref fAnnualSalary, value); }
        }
        string fPeriodSalary;
        public string PeriodSalary
        {
            get { return fPeriodSalary; }
            set { SetPropertyValue<string>(nameof(PeriodSalary), ref fPeriodSalary, value); }
        }
        string fOverrideAnnualBonusCalcRecurrence;
        public string OverrideAnnualBonusCalcRecurrence
        {
            get { return fOverrideAnnualBonusCalcRecurrence; }
            set { SetPropertyValue<string>(nameof(OverrideAnnualBonusCalcRecurrence), ref fOverrideAnnualBonusCalcRecurrence, value); }
        }
        string fCalendarMonth;
        public string CalendarMonth
        {
            get { return fCalendarMonth; }
            set { SetPropertyValue<string>(nameof(CalendarMonth), ref fCalendarMonth, value); }
        }
        string fPeriodInMonth;
        public string PeriodInMonth
        {
            get { return fPeriodInMonth; }
            set { SetPropertyValue<string>(nameof(PeriodInMonth), ref fPeriodInMonth, value); }
        }
        string fDefaultShiftsPerPeriod;
        public string DefaultShiftsPerPeriod
        {
            get { return fDefaultShiftsPerPeriod; }
            set { SetPropertyValue<string>(nameof(DefaultShiftsPerPeriod), ref fDefaultShiftsPerPeriod, value); }
        }
        string fRatePerDay;
        public string RatePerDay
        {
            get { return fRatePerDay; }
            set { SetPropertyValue<string>(nameof(RatePerDay), ref fRatePerDay, value); }
        }
        string fRatePerHour;
        public string RatePerHour
        {
            get { return fRatePerHour; }
            set { SetPropertyValue<string>(nameof(RatePerHour), ref fRatePerHour, value); }
        }
        DateTime fPensionFundStartDate;
        public DateTime PensionFundStartDate
        {
            get { return fPensionFundStartDate; }
            set { SetPropertyValue<DateTime>(nameof(PensionFundStartDate), ref fPensionFundStartDate, value); }
        }
        DateTime fProvidentFundStartDate;
        public DateTime ProvidentFundStartDate
        {
            get { return fProvidentFundStartDate; }
            set { SetPropertyValue<DateTime>(nameof(ProvidentFundStartDate), ref fProvidentFundStartDate, value); }
        }
        string fZoneCodes;
        public string ZoneCodes
        {
            get { return fZoneCodes; }
            set { SetPropertyValue<string>(nameof(ZoneCodes), ref fZoneCodes, value); }
        }
        string fIncreaseReasonTypeCode;
        public string IncreaseReasonTypeCode
        {
            get { return fIncreaseReasonTypeCode; }
            set { SetPropertyValue<string>(nameof(IncreaseReasonTypeCode), ref fIncreaseReasonTypeCode, value); }
        }
        DateTime fMedicalStartDate;
        public DateTime MedicalStartDate
        {
            get { return fMedicalStartDate; }
            set { SetPropertyValue<DateTime>(nameof(MedicalStartDate), ref fMedicalStartDate, value); }
        }
        string fAddRate1;
        public string AddRate1
        {
            get { return fAddRate1; }
            set { SetPropertyValue<string>(nameof(AddRate1), ref fAddRate1, value); }
        }
        string fAddRate2;
        public string AddRate2
        {
            get { return fAddRate2; }
            set { SetPropertyValue<string>(nameof(AddRate2), ref fAddRate2, value); }
        }
        string fAddRate3;
        public string AddRate3
        {
            get { return fAddRate3; }
            set { SetPropertyValue<string>(nameof(AddRate3), ref fAddRate3, value); }
        }
        string fAddRate4;
        public string AddRate4
        {
            get { return fAddRate4; }
            set { SetPropertyValue<string>(nameof(AddRate4), ref fAddRate4, value); }
        }
        string fAddRate5;
        public string AddRate5
        {
            get { return fAddRate5; }
            set { SetPropertyValue<string>(nameof(AddRate5), ref fAddRate5, value); }
        }
        DateTime fAddDate1;
        public DateTime AddDate1
        {
            get { return fAddDate1; }
            set { SetPropertyValue<DateTime>(nameof(AddDate1), ref fAddDate1, value); }
        }
        DateTime fAddDate2;
        public DateTime AddDate2
        {
            get { return fAddDate2; }
            set { SetPropertyValue<DateTime>(nameof(AddDate2), ref fAddDate2, value); }
        }
        DateTime fAddDate3;
        public DateTime AddDate3
        {
            get { return fAddDate3; }
            set { SetPropertyValue<DateTime>(nameof(AddDate3), ref fAddDate3, value); }
        }
        DateTime fAddDate4;
        public DateTime AddDate4
        {
            get { return fAddDate4; }
            set { SetPropertyValue<DateTime>(nameof(AddDate4), ref fAddDate4, value); }
        }
        DateTime fAddDate5;
        public DateTime AddDate5
        {
            get { return fAddDate5; }
            set { SetPropertyValue<DateTime>(nameof(AddDate5), ref fAddDate5, value); }
        }
        string fLegallyRetiredforTaxPurpose;
        public string LegallyRetiredforTaxPurpose
        {
            get { return fLegallyRetiredforTaxPurpose; }
            set { SetPropertyValue<string>(nameof(LegallyRetiredforTaxPurpose), ref fLegallyRetiredforTaxPurpose, value); }
        }
        string fForeignIncome;
        public string ForeignIncome
        {
            get { return fForeignIncome; }
            set { SetPropertyValue<string>(nameof(ForeignIncome), ref fForeignIncome, value); }
        }
        string fTaxStatusCode;
        public string TaxStatusCode
        {
            get { return fTaxStatusCode; }
            set { SetPropertyValue<string>(nameof(TaxStatusCode), ref fTaxStatusCode, value); }
        }
        DateTime fTaxStartDate;
        public DateTime TaxStartDate
        {
            get { return fTaxStartDate; }
            set { SetPropertyValue<DateTime>(nameof(TaxStartDate), ref fTaxStartDate, value); }
        }
        string fTaxCalculation;
        public string TaxCalculation
        {
            get { return fTaxCalculation; }
            set { SetPropertyValue<string>(nameof(TaxCalculation), ref fTaxCalculation, value); }
        }
        string fDirectiveNumber;
        public string DirectiveNumber
        {
            get { return fDirectiveNumber; }
            set { SetPropertyValue<string>(nameof(DirectiveNumber), ref fDirectiveNumber, value); }
        }
        string fDirectivePercentage;
        public string DirectivePercentage
        {
            get { return fDirectivePercentage; }
            set { SetPropertyValue<string>(nameof(DirectivePercentage), ref fDirectivePercentage, value); }
        }
        string fDirectiveTaxAmount;
        public string DirectiveTaxAmount
        {
            get { return fDirectiveTaxAmount; }
            set { SetPropertyValue<string>(nameof(DirectiveTaxAmount), ref fDirectiveTaxAmount, value); }
        }
        string fDeemedRemuneration;
        public string DeemedRemuneration
        {
            get { return fDeemedRemuneration; }
            set { SetPropertyValue<string>(nameof(DeemedRemuneration), ref fDeemedRemuneration, value); }
        }
        string fUseTaxValue1;
        public string UseTaxValue1
        {
            get { return fUseTaxValue1; }
            set { SetPropertyValue<string>(nameof(UseTaxValue1), ref fUseTaxValue1, value); }
        }
        string fUseTaxValue2;
        public string UseTaxValue2
        {
            get { return fUseTaxValue2; }
            set { SetPropertyValue<string>(nameof(UseTaxValue2), ref fUseTaxValue2, value); }
        }
        string fRemunerationDefinitionHeaderCode;
        public string RemunerationDefinitionHeaderCode
        {
            get { return fRemunerationDefinitionHeaderCode; }
            set { SetPropertyValue<string>(nameof(RemunerationDefinitionHeaderCode), ref fRemunerationDefinitionHeaderCode, value); }
        }
        string fUseWork;
        public string UseWork
        {
            get { return fUseWork; }
            set { SetPropertyValue<string>(nameof(UseWork), ref fUseWork, value); }
        }
        string fUsePhysical;
        public string UsePhysical
        {
            get { return fUsePhysical; }
            set { SetPropertyValue<string>(nameof(UsePhysical), ref fUsePhysical, value); }
        }
        string fUsePostal;
        public string UsePostal
        {
            get { return fUsePostal; }
            set { SetPropertyValue<string>(nameof(UsePostal), ref fUsePostal, value); }
        }
        string fAddressServiceTypeCode;
        public string AddressServiceTypeCode
        {
            get { return fAddressServiceTypeCode; }
            set { SetPropertyValue<string>(nameof(AddressServiceTypeCode), ref fAddressServiceTypeCode, value); }
        }
        string fCorrespondenceAddress;
        public string CorrespondenceAddress
        {
            get { return fCorrespondenceAddress; }
            set { SetPropertyValue<string>(nameof(CorrespondenceAddress), ref fCorrespondenceAddress, value); }
        }
        string fUnitPostalNumber;
        public string UnitPostalNumber
        {
            get { return fUnitPostalNumber; }
            set { SetPropertyValue<string>(nameof(UnitPostalNumber), ref fUnitPostalNumber, value); }
        }
        string fComplex;
        public string Complex
        {
            get { return fComplex; }
            set { SetPropertyValue<string>(nameof(Complex), ref fComplex, value); }
        }
        string fLevelFloor;
        public string LevelFloor
        {
            get { return fLevelFloor; }
            set { SetPropertyValue<string>(nameof(LevelFloor), ref fLevelFloor, value); }
        }
        string fBlock;
        public string Block
        {
            get { return fBlock; }
            set { SetPropertyValue<string>(nameof(Block), ref fBlock, value); }
        }
        string fStreetNumber;
        public string StreetNumber
        {
            get { return fStreetNumber; }
            set { SetPropertyValue<string>(nameof(StreetNumber), ref fStreetNumber, value); }
        }
        string fStreetFarmName;
        public string StreetFarmName
        {
            get { return fStreetFarmName; }
            set { SetPropertyValue<string>(nameof(StreetFarmName), ref fStreetFarmName, value); }
        }
        string fSuburbDistrict;
        public string SuburbDistrict
        {
            get { return fSuburbDistrict; }
            set { SetPropertyValue<string>(nameof(SuburbDistrict), ref fSuburbDistrict, value); }
        }
        string fDistrictCode;
        public string DistrictCode
        {
            get { return fDistrictCode; }
            set { SetPropertyValue<string>(nameof(DistrictCode), ref fDistrictCode, value); }
        }
        string fCityTown;
        public string CityTown
        {
            get { return fCityTown; }
            set { SetPropertyValue<string>(nameof(CityTown), ref fCityTown, value); }
        }
        string fProvince;
        public string Province
        {
            get { return fProvince; }
            set { SetPropertyValue<string>(nameof(Province), ref fProvince, value); }
        }
        string fPostalCode;
        public string PostalCode
        {
            get { return fPostalCode; }
            set { SetPropertyValue<string>(nameof(PostalCode), ref fPostalCode, value); }
        }
        string fPostalAgency;
        public string PostalAgency
        {
            get { return fPostalAgency; }
            set { SetPropertyValue<string>(nameof(PostalAgency), ref fPostalAgency, value); }
        }
        string fPostOffice;
        public string PostOffice
        {
            get { return fPostOffice; }
            set { SetPropertyValue<string>(nameof(PostOffice), ref fPostOffice, value); }
        }
        string fPostalAddressNumber;
        public string PostalAddressNumber
        {
            get { return fPostalAddressNumber; }
            set { SetPropertyValue<string>(nameof(PostalAddressNumber), ref fPostalAddressNumber, value); }
        }
        string fOtherServiceType;
        public string OtherServiceType
        {
            get { return fOtherServiceType; }
            set { SetPropertyValue<string>(nameof(OtherServiceType), ref fOtherServiceType, value); }
        }
        string fCareOf;
        public string CareOf
        {
            get { return fCareOf; }
            set { SetPropertyValue<string>(nameof(CareOf), ref fCareOf, value); }
        }
        string fCareOfName;
        public string CareOfName
        {
            get { return fCareOfName; }
            set { SetPropertyValue<string>(nameof(CareOfName), ref fCareOfName, value); }
        }
        string fCountryCode;
        public string CountryCode
        {
            get { return fCountryCode; }
            set { SetPropertyValue<string>(nameof(CountryCode), ref fCountryCode, value); }
        }
        string fUseWork1;
        public string UseWork1
        {
            get { return fUseWork1; }
            set { SetPropertyValue<string>(nameof(UseWork1), ref fUseWork1, value); }
        }
        string fUsePhysical1;
        public string UsePhysical1
        {
            get { return fUsePhysical1; }
            set { SetPropertyValue<string>(nameof(UsePhysical1), ref fUsePhysical1, value); }
        }
        string fUsePostal1;
        public string UsePostal1
        {
            get { return fUsePostal1; }
            set { SetPropertyValue<string>(nameof(UsePostal1), ref fUsePostal1, value); }
        }
        string fAddressServiceTypeCode1;
        public string AddressServiceTypeCode1
        {
            get { return fAddressServiceTypeCode1; }
            set { SetPropertyValue<string>(nameof(AddressServiceTypeCode1), ref fAddressServiceTypeCode1, value); }
        }
        string fCorrespondenceAddress1;
        public string CorrespondenceAddress1
        {
            get { return fCorrespondenceAddress1; }
            set { SetPropertyValue<string>(nameof(CorrespondenceAddress1), ref fCorrespondenceAddress1, value); }
        }
        string fUnitPostalNumber1;
        public string UnitPostalNumber1
        {
            get { return fUnitPostalNumber1; }
            set { SetPropertyValue<string>(nameof(UnitPostalNumber1), ref fUnitPostalNumber1, value); }
        }
        string fComplex1;
        public string Complex1
        {
            get { return fComplex1; }
            set { SetPropertyValue<string>(nameof(Complex1), ref fComplex1, value); }
        }
        string fLevelFloor1;
        public string LevelFloor1
        {
            get { return fLevelFloor1; }
            set { SetPropertyValue<string>(nameof(LevelFloor1), ref fLevelFloor1, value); }
        }
        string fBlock1;
        public string Block1
        {
            get { return fBlock1; }
            set { SetPropertyValue<string>(nameof(Block1), ref fBlock1, value); }
        }
        string fStreetNumber1;
        public string StreetNumber1
        {
            get { return fStreetNumber1; }
            set { SetPropertyValue<string>(nameof(StreetNumber1), ref fStreetNumber1, value); }
        }
        string fStreetFarmName1;
        public string StreetFarmName1
        {
            get { return fStreetFarmName1; }
            set { SetPropertyValue<string>(nameof(StreetFarmName1), ref fStreetFarmName1, value); }
        }
        string fSuburbDistrict1;
        public string SuburbDistrict1
        {
            get { return fSuburbDistrict1; }
            set { SetPropertyValue<string>(nameof(SuburbDistrict1), ref fSuburbDistrict1, value); }
        }
        string fDistrictCode1;
        public string DistrictCode1
        {
            get { return fDistrictCode1; }
            set { SetPropertyValue<string>(nameof(DistrictCode1), ref fDistrictCode1, value); }
        }
        string fCityTown1;
        public string CityTown1
        {
            get { return fCityTown1; }
            set { SetPropertyValue<string>(nameof(CityTown1), ref fCityTown1, value); }
        }
        string fProvince1;
        public string Province1
        {
            get { return fProvince1; }
            set { SetPropertyValue<string>(nameof(Province1), ref fProvince1, value); }
        }
        string fPostalCode1;
        public string PostalCode1
        {
            get { return fPostalCode1; }
            set { SetPropertyValue<string>(nameof(PostalCode1), ref fPostalCode1, value); }
        }
        string fPostalAgency1;
        public string PostalAgency1
        {
            get { return fPostalAgency1; }
            set { SetPropertyValue<string>(nameof(PostalAgency1), ref fPostalAgency1, value); }
        }
        string fPostOffice1;
        public string PostOffice1
        {
            get { return fPostOffice1; }
            set { SetPropertyValue<string>(nameof(PostOffice1), ref fPostOffice1, value); }
        }
        string fPostalAddressNumber1;
        public string PostalAddressNumber1
        {
            get { return fPostalAddressNumber1; }
            set { SetPropertyValue<string>(nameof(PostalAddressNumber1), ref fPostalAddressNumber1, value); }
        }
        string fOtherServiceType1;
        public string OtherServiceType1
        {
            get { return fOtherServiceType1; }
            set { SetPropertyValue<string>(nameof(OtherServiceType1), ref fOtherServiceType1, value); }
        }
        string fCareOf1;
        public string CareOf1
        {
            get { return fCareOf1; }
            set { SetPropertyValue<string>(nameof(CareOf1), ref fCareOf1, value); }
        }
        string fCareOfName1;
        public string CareOfName1
        {
            get { return fCareOfName1; }
            set { SetPropertyValue<string>(nameof(CareOfName1), ref fCareOfName1, value); }
        }
        string fCountryCode1;
        public string CountryCode1
        {
            get { return fCountryCode1; }
            set { SetPropertyValue<string>(nameof(CountryCode1), ref fCountryCode1, value); }
        }
        string fUseWork2;
        public string UseWork2
        {
            get { return fUseWork2; }
            set { SetPropertyValue<string>(nameof(UseWork2), ref fUseWork2, value); }
        }
        string fUsePhysical2;
        public string UsePhysical2
        {
            get { return fUsePhysical2; }
            set { SetPropertyValue<string>(nameof(UsePhysical2), ref fUsePhysical2, value); }
        }
        string fUsePostal2;
        public string UsePostal2
        {
            get { return fUsePostal2; }
            set { SetPropertyValue<string>(nameof(UsePostal2), ref fUsePostal2, value); }
        }
        string fAddressServiceTypeCode2;
        public string AddressServiceTypeCode2
        {
            get { return fAddressServiceTypeCode2; }
            set { SetPropertyValue<string>(nameof(AddressServiceTypeCode2), ref fAddressServiceTypeCode2, value); }
        }
        string fCorrespondenceAddress2;
        public string CorrespondenceAddress2
        {
            get { return fCorrespondenceAddress2; }
            set { SetPropertyValue<string>(nameof(CorrespondenceAddress2), ref fCorrespondenceAddress2, value); }
        }
        string fUnitPostalNumber2;
        public string UnitPostalNumber2
        {
            get { return fUnitPostalNumber2; }
            set { SetPropertyValue<string>(nameof(UnitPostalNumber2), ref fUnitPostalNumber2, value); }
        }
        string fComplex2;
        public string Complex2
        {
            get { return fComplex2; }
            set { SetPropertyValue<string>(nameof(Complex2), ref fComplex2, value); }
        }
        string fLevelFloor2;
        public string LevelFloor2
        {
            get { return fLevelFloor2; }
            set { SetPropertyValue<string>(nameof(LevelFloor2), ref fLevelFloor2, value); }
        }
        string fBlock2;
        public string Block2
        {
            get { return fBlock2; }
            set { SetPropertyValue<string>(nameof(Block2), ref fBlock2, value); }
        }
        string fStreetNumber2;
        public string StreetNumber2
        {
            get { return fStreetNumber2; }
            set { SetPropertyValue<string>(nameof(StreetNumber2), ref fStreetNumber2, value); }
        }
        string fStreetFarmName2;
        public string StreetFarmName2
        {
            get { return fStreetFarmName2; }
            set { SetPropertyValue<string>(nameof(StreetFarmName2), ref fStreetFarmName2, value); }
        }
        string fSuburbDistrict2;
        public string SuburbDistrict2
        {
            get { return fSuburbDistrict2; }
            set { SetPropertyValue<string>(nameof(SuburbDistrict2), ref fSuburbDistrict2, value); }
        }
        string fDistrictCode2;
        public string DistrictCode2
        {
            get { return fDistrictCode2; }
            set { SetPropertyValue<string>(nameof(DistrictCode2), ref fDistrictCode2, value); }
        }
        string fCityTown2;
        public string CityTown2
        {
            get { return fCityTown2; }
            set { SetPropertyValue<string>(nameof(CityTown2), ref fCityTown2, value); }
        }
        string fProvince2;
        public string Province2
        {
            get { return fProvince2; }
            set { SetPropertyValue<string>(nameof(Province2), ref fProvince2, value); }
        }
        string fPostalCode2;
        public string PostalCode2
        {
            get { return fPostalCode2; }
            set { SetPropertyValue<string>(nameof(PostalCode2), ref fPostalCode2, value); }
        }
        string fPostalAgency2;
        public string PostalAgency2
        {
            get { return fPostalAgency2; }
            set { SetPropertyValue<string>(nameof(PostalAgency2), ref fPostalAgency2, value); }
        }
        string fPostOffice2;
        public string PostOffice2
        {
            get { return fPostOffice2; }
            set { SetPropertyValue<string>(nameof(PostOffice2), ref fPostOffice2, value); }
        }
        string fPostalAddressNumber2;
        public string PostalAddressNumber2
        {
            get { return fPostalAddressNumber2; }
            set { SetPropertyValue<string>(nameof(PostalAddressNumber2), ref fPostalAddressNumber2, value); }
        }
        string fOtherServiceType2;
        public string OtherServiceType2
        {
            get { return fOtherServiceType2; }
            set { SetPropertyValue<string>(nameof(OtherServiceType2), ref fOtherServiceType2, value); }
        }
        string fCareOf2;
        public string CareOf2
        {
            get { return fCareOf2; }
            set { SetPropertyValue<string>(nameof(CareOf2), ref fCareOf2, value); }
        }
        string fCareOfName2;
        public string CareOfName2
        {
            get { return fCareOfName2; }
            set { SetPropertyValue<string>(nameof(CareOfName2), ref fCareOfName2, value); }
        }
        string fCountryCode2;
        public string CountryCode2
        {
            get { return fCountryCode2; }
            set { SetPropertyValue<string>(nameof(CountryCode2), ref fCountryCode2, value); }
        }
        string fAccountHolderRelationship;
        public string AccountHolderRelationship
        {
            get { return fAccountHolderRelationship; }
            set { SetPropertyValue<string>(nameof(AccountHolderRelationship), ref fAccountHolderRelationship, value); }
        }
        string fAccountName;
        public string AccountName
        {
            get { return fAccountName; }
            set { SetPropertyValue<string>(nameof(AccountName), ref fAccountName, value); }
        }
        string fBankCode;
        public string BankCode
        {
            get { return fBankCode; }
            set { SetPropertyValue<string>(nameof(BankCode), ref fBankCode, value); }
        }
        string fBankDescription;
        public string BankDescription
        {
            get { return fBankDescription; }
            set { SetPropertyValue<string>(nameof(BankDescription), ref fBankDescription, value); }
        }
        string fAccountTypeCode;
        public string AccountTypeCode
        {
            get { return fAccountTypeCode; }
            set { SetPropertyValue<string>(nameof(AccountTypeCode), ref fAccountTypeCode, value); }
        }
        string fAccountNo;
        public string AccountNo
        {
            get { return fAccountNo; }
            set { SetPropertyValue<string>(nameof(AccountNo), ref fAccountNo, value); }
        }
        string fBankBranchCode;
        public string BankBranchCode
        {
            get { return fBankBranchCode; }
            set { SetPropertyValue<string>(nameof(BankBranchCode), ref fBankBranchCode, value); }
        }
        string fBankBranchDescription;
        public string BankBranchDescription
        {
            get { return fBankBranchDescription; }
            set { SetPropertyValue<string>(nameof(BankBranchDescription), ref fBankBranchDescription, value); }
        }
        string fCreditLineNumber;
        public string CreditLineNumber
        {
            get { return fCreditLineNumber; }
            set { SetPropertyValue<string>(nameof(CreditLineNumber), ref fCreditLineNumber, value); }
        }
        string fCcy;
        public string Ccy
        {
            get { return fCcy; }
            set { SetPropertyValue<string>(nameof(Ccy), ref fCcy, value); }
        }
        string fDriversLicCountryCode;
        public string DriversLicCountryCode
        {
            get { return fDriversLicCountryCode; }
            set { SetPropertyValue<string>(nameof(DriversLicCountryCode), ref fDriversLicCountryCode, value); }
        }
        DateTime fIssueDate;
        public DateTime IssueDate
        {
            get { return fIssueDate; }
            set { SetPropertyValue<DateTime>(nameof(IssueDate), ref fIssueDate, value); }
        }
        DateTime fExpiryDate;
        public DateTime ExpiryDate
        {
            get { return fExpiryDate; }
            set { SetPropertyValue<DateTime>(nameof(ExpiryDate), ref fExpiryDate, value); }
        }
        string fLicenseNumber;
        public string LicenseNumber
        {
            get { return fLicenseNumber; }
            set { SetPropertyValue<string>(nameof(LicenseNumber), ref fLicenseNumber, value); }
        }
        string fLicenseCategoriesTypeCode;
        public string LicenseCategoriesTypeCode
        {
            get { return fLicenseCategoriesTypeCode; }
            set { SetPropertyValue<string>(nameof(LicenseCategoriesTypeCode), ref fLicenseCategoriesTypeCode, value); }
        }
        string fLicenseRestrictionsTypeCode;
        public string LicenseRestrictionsTypeCode
        {
            get { return fLicenseRestrictionsTypeCode; }
            set { SetPropertyValue<string>(nameof(LicenseRestrictionsTypeCode), ref fLicenseRestrictionsTypeCode, value); }
        }
        string fFWLPolicyCode;
        public string FWLPolicyCode
        {
            get { return fFWLPolicyCode; }
            set { SetPropertyValue<string>(nameof(FWLPolicyCode), ref fFWLPolicyCode, value); }
        }
        DateTime fEffectiveDate;
        public DateTime EffectiveDate
        {
            get { return fEffectiveDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveDate), ref fEffectiveDate, value); }
        }
        DateTime fFWLExpiryDate;
        public DateTime FWLExpiryDate
        {
            get { return fFWLExpiryDate; }
            set { SetPropertyValue<DateTime>(nameof(FWLExpiryDate), ref fFWLExpiryDate, value); }
        }
        string fPermitNumber;
        public string PermitNumber
        {
            get { return fPermitNumber; }
            set { SetPropertyValue<string>(nameof(PermitNumber), ref fPermitNumber, value); }
        }
        string fCancellationDate;
        public string CancellationDate
        {
            get { return fCancellationDate; }
            set { SetPropertyValue<string>(nameof(CancellationDate), ref fCancellationDate, value); }
        }
        DateTime fFWLIssueDate;
        public DateTime FWLIssueDate
        {
            get { return fFWLIssueDate; }
            set { SetPropertyValue<DateTime>(nameof(FWLIssueDate), ref fFWLIssueDate, value); }
        }
        DateTime fArrivalDate;
        public DateTime ArrivalDate
        {
            get { return fArrivalDate; }
            set { SetPropertyValue<DateTime>(nameof(ArrivalDate), ref fArrivalDate, value); }
        }
        DateTime fApplicationDate;
        public DateTime ApplicationDate
        {
            get { return fApplicationDate; }
            set { SetPropertyValue<DateTime>(nameof(ApplicationDate), ref fApplicationDate, value); }
        }
        string fCPFVoluntaryPolicyCode;
        public string CPFVoluntaryPolicyCode
        {
            get { return fCPFVoluntaryPolicyCode; }
            set { SetPropertyValue<string>(nameof(CPFVoluntaryPolicyCode), ref fCPFVoluntaryPolicyCode, value); }
        }
        string fSocialSecurityFundTypeCode;
        public string SocialSecurityFundTypeCode
        {
            get { return fSocialSecurityFundTypeCode; }
            set { SetPropertyValue<string>(nameof(SocialSecurityFundTypeCode), ref fSocialSecurityFundTypeCode, value); }
        }
        string fSDLExempt;
        public string SDLExempt
        {
            get { return fSDLExempt; }
            set { SetPropertyValue<string>(nameof(SDLExempt), ref fSDLExempt, value); }
        }
        string fRTNumber;
        public string RTNumber
        {
            get { return fRTNumber; }
            set { SetPropertyValue<string>(nameof(RTNumber), ref fRTNumber, value); }
        }
        string fRWNumber;
        public string RWNumber
        {
            get { return fRWNumber; }
            set { SetPropertyValue<string>(nameof(RWNumber), ref fRWNumber, value); }
        }
        string fKartuKeluargaNumber;
        public string KartuKeluargaNumber
        {
            get { return fKartuKeluargaNumber; }
            set { SetPropertyValue<string>(nameof(KartuKeluargaNumber), ref fKartuKeluargaNumber, value); }
        }
        string fHealthFacilityCode;
        public string HealthFacilityCode
        {
            get { return fHealthFacilityCode; }
            set { SetPropertyValue<string>(nameof(HealthFacilityCode), ref fHealthFacilityCode, value); }
        }
        string fBPJSPensionNumber;
        public string BPJSPensionNumber
        {
            get { return fBPJSPensionNumber; }
            set { SetPropertyValue<string>(nameof(BPJSPensionNumber), ref fBPJSPensionNumber, value); }
        }
        string fJPKNumber;
        public string JPKNumber
        {
            get { return fJPKNumber; }
            set { SetPropertyValue<string>(nameof(JPKNumber), ref fJPKNumber, value); }
        }
        string fKPJNumber;
        public string KPJNumber
        {
            get { return fKPJNumber; }
            set { SetPropertyValue<string>(nameof(KPJNumber), ref fKPJNumber, value); }
        }
        string fEmploymentStatus;
        public string EmploymentStatus
        {
            get { return fEmploymentStatus; }
            set { SetPropertyValue<string>(nameof(EmploymentStatus), ref fEmploymentStatus, value); }
        }
        string fBPJSKesehatan;
        public string BPJSKesehatan
        {
            get { return fBPJSKesehatan; }
            set { SetPropertyValue<string>(nameof(BPJSKesehatan), ref fBPJSKesehatan, value); }
        }
        string fGovernmentAssistance;
        public string GovernmentAssistance
        {
            get { return fGovernmentAssistance; }
            set { SetPropertyValue<string>(nameof(GovernmentAssistance), ref fGovernmentAssistance, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fLastChanged;
        public DateTime LastChanged
        {
            get { return fLastChanged; }
            set { SetPropertyValue<DateTime>(nameof(LastChanged), ref fLastChanged, value); }
        }
        string fQueueComment;
        [Size(SizeAttribute.Unlimited)]
        public string QueueComment
        {
            get { return fQueueComment; }
            set { SetPropertyValue<string>(nameof(QueueComment), ref fQueueComment, value); }
        }
        string fQueueFilter;
        [Size(SizeAttribute.Unlimited)]
        public string QueueFilter
        {
            get { return fQueueFilter; }
            set { SetPropertyValue<string>(nameof(QueueFilter), ref fQueueFilter, value); }
        }
        string fStatusCode;
        public string StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<string>(nameof(StatusCode), ref fStatusCode, value); }
        }
        string fStatusMessage;
        [Size(SizeAttribute.Unlimited)]
        public string StatusMessage
        {
            get { return fStatusMessage; }
            set { SetPropertyValue<string>(nameof(StatusMessage), ref fStatusMessage, value); }
        }
        string fWarningCode;
        public string WarningCode
        {
            get { return fWarningCode; }
            set { SetPropertyValue<string>(nameof(WarningCode), ref fWarningCode, value); }
        }
        string fWarningMessage;
        [Size(SizeAttribute.Unlimited)]
        public string WarningMessage
        {
            get { return fWarningMessage; }
            set { SetPropertyValue<string>(nameof(WarningMessage), ref fWarningMessage, value); }
        }
        string fErrorCode;
        public string ErrorCode
        {
            get { return fErrorCode; }
            set { SetPropertyValue<string>(nameof(ErrorCode), ref fErrorCode, value); }
        }
        string fErrorMessage;
        [Size(SizeAttribute.Unlimited)]
        public string ErrorMessage
        {
            get { return fErrorMessage; }
            set { SetPropertyValue<string>(nameof(ErrorMessage), ref fErrorMessage, value); }
        }
    }

}
