//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.FinancialQueue")]
    public partial class AIFinancialQueue : XPObject
    {
        string fEventCode;
        public string EventCode
        {
            get { return fEventCode; }
            set { SetPropertyValue<string>(nameof(EventCode), ref fEventCode, value); }
        }
        string fEventDescription;
        public string EventDescription
        {
            get { return fEventDescription; }
            set { SetPropertyValue<string>(nameof(EventDescription), ref fEventDescription, value); }
        }
        short fEventSequenceID;
        public short EventSequenceID
        {
            get { return fEventSequenceID; }
            set { SetPropertyValue<short>(nameof(EventSequenceID), ref fEventSequenceID, value); }
        }
        DateTime fEffectiveStartDate;
        public DateTime EffectiveStartDate
        {
            get { return fEffectiveStartDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveStartDate), ref fEffectiveStartDate, value); }
        }
        DateTime fEffectiveEndDate;
        public DateTime EffectiveEndDate
        {
            get { return fEffectiveEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveEndDate), ref fEffectiveEndDate, value); }
        }
        string fCountryCodeIndicator;
        public string CountryCodeIndicator
        {
            get { return fCountryCodeIndicator; }
            set { SetPropertyValue<string>(nameof(CountryCodeIndicator), ref fCountryCodeIndicator, value); }
        }
        string fCompanyCode;
        public string CompanyCode
        {
            get { return fCompanyCode; }
            set { SetPropertyValue<string>(nameof(CompanyCode), ref fCompanyCode, value); }
        }
        string fEmployeeCode;
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fWageTypeCode;
        public string WageTypeCode
        {
            get { return fWageTypeCode; }
            set { SetPropertyValue<string>(nameof(WageTypeCode), ref fWageTypeCode, value); }
        }
        string fAmount;
        public string Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<string>(nameof(Amount), ref fAmount, value); }
        }
        string fCcy;
        public string Ccy
        {
            get { return fCcy; }
            set { SetPropertyValue<string>(nameof(Ccy), ref fCcy, value); }
        }
        string fOneTimePayment;
        public string OneTimePayment
        {
            get { return fOneTimePayment; }
            set { SetPropertyValue<string>(nameof(OneTimePayment), ref fOneTimePayment, value); }
        }
        string fFrequency;
        public string Frequency
        {
            get { return fFrequency; }
            set { SetPropertyValue<string>(nameof(Frequency), ref fFrequency, value); }
        }
        string fEffectiveDate;
        public string EffectiveDate
        {
            get { return fEffectiveDate; }
            set { SetPropertyValue<string>(nameof(EffectiveDate), ref fEffectiveDate, value); }
        }
        string fEndDate;
        public string EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<string>(nameof(EndDate), ref fEndDate, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fLastChanged;
        public DateTime LastChanged
        {
            get { return fLastChanged; }
            set { SetPropertyValue<DateTime>(nameof(LastChanged), ref fLastChanged, value); }
        }
        string fQueueComment;
        [Size(SizeAttribute.Unlimited)]
        public string QueueComment
        {
            get { return fQueueComment; }
            set { SetPropertyValue<string>(nameof(QueueComment), ref fQueueComment, value); }
        }
        string fQueueFilter;
        [Size(SizeAttribute.Unlimited)]
        public string QueueFilter
        {
            get { return fQueueFilter; }
            set { SetPropertyValue<string>(nameof(QueueFilter), ref fQueueFilter, value); }
        }
        string fStatusCode;
        public string StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<string>(nameof(StatusCode), ref fStatusCode, value); }
        }
        string fStatusMessage;
        [Size(SizeAttribute.Unlimited)]
        public string StatusMessage
        {
            get { return fStatusMessage; }
            set { SetPropertyValue<string>(nameof(StatusMessage), ref fStatusMessage, value); }
        }
        string fWarningCode;
        public string WarningCode
        {
            get { return fWarningCode; }
            set { SetPropertyValue<string>(nameof(WarningCode), ref fWarningCode, value); }
        }
        string fWarningMessage;
        [Size(SizeAttribute.Unlimited)]
        public string WarningMessage
        {
            get { return fWarningMessage; }
            set { SetPropertyValue<string>(nameof(WarningMessage), ref fWarningMessage, value); }
        }
        string fErrorCode;
        public string ErrorCode
        {
            get { return fErrorCode; }
            set { SetPropertyValue<string>(nameof(ErrorCode), ref fErrorCode, value); }
        }
        string fErrorMessage;
        [Size(SizeAttribute.Unlimited)]
        public string ErrorMessage
        {
            get { return fErrorMessage; }
            set { SetPropertyValue<string>(nameof(ErrorMessage), ref fErrorMessage, value); }
        }
    }

}
