//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    public partial class AILeaveTransactionQueue : XPObject
    {
        string fEventCode;
        public string EventCode
        {
            get { return fEventCode; }
            set { SetPropertyValue<string>(nameof(EventCode), ref fEventCode, value); }
        }
        string fEventDescription;
        public string EventDescription
        {
            get { return fEventDescription; }
            set { SetPropertyValue<string>(nameof(EventDescription), ref fEventDescription, value); }
        }
        string fEventSequenceID;
        public string EventSequenceID
        {
            get { return fEventSequenceID; }
            set { SetPropertyValue<string>(nameof(EventSequenceID), ref fEventSequenceID, value); }
        }
        DateTime fEffectiveStartDate;
        public DateTime EffectiveStartDate
        {
            get { return fEffectiveStartDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveStartDate), ref fEffectiveStartDate, value); }
        }
        DateTime fEffectiveEndDate;
        public DateTime EffectiveEndDate
        {
            get { return fEffectiveEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveEndDate), ref fEffectiveEndDate, value); }
        }
        string fCountryCodeIndicator;
        public string CountryCodeIndicator
        {
            get { return fCountryCodeIndicator; }
            set { SetPropertyValue<string>(nameof(CountryCodeIndicator), ref fCountryCodeIndicator, value); }
        }
        string fCompanyCode;
        public string CompanyCode
        {
            get { return fCompanyCode; }
            set { SetPropertyValue<string>(nameof(CompanyCode), ref fCompanyCode, value); }
        }
        string fEmployeeCode;
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fLeaveTypeCode;
        public string LeaveTypeCode
        {
            get { return fLeaveTypeCode; }
            set { SetPropertyValue<string>(nameof(LeaveTypeCode), ref fLeaveTypeCode, value); }
        }
        string fLeaveCode;
        public string LeaveCode
        {
            get { return fLeaveCode; }
            set { SetPropertyValue<string>(nameof(LeaveCode), ref fLeaveCode, value); }
        }
        DateTime fFromDate;
        public DateTime FromDate
        {
            get { return fFromDate; }
            set { SetPropertyValue<DateTime>(nameof(FromDate), ref fFromDate, value); }
        }
        DateTime fToDate;
        public DateTime ToDate
        {
            get { return fToDate; }
            set { SetPropertyValue<DateTime>(nameof(ToDate), ref fToDate, value); }
        }
        string fUnitsTaken;
        public string UnitsTaken
        {
            get { return fUnitsTaken; }
            set { SetPropertyValue<string>(nameof(UnitsTaken), ref fUnitsTaken, value); }
        }
        string fUnit;
        public string Unit
        {
            get { return fUnit; }
            set { SetPropertyValue<string>(nameof(Unit), ref fUnit, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fLastChanged;
        public DateTime LastChanged
        {
            get { return fLastChanged; }
            set { SetPropertyValue<DateTime>(nameof(LastChanged), ref fLastChanged, value); }
        }
        string fQueueComment;
        [Size(SizeAttribute.Unlimited)]
        public string QueueComment
        {
            get { return fQueueComment; }
            set { SetPropertyValue<string>(nameof(QueueComment), ref fQueueComment, value); }
        }
        string fQueueFilter;
        [Size(SizeAttribute.Unlimited)]
        public string QueueFilter
        {
            get { return fQueueFilter; }
            set { SetPropertyValue<string>(nameof(QueueFilter), ref fQueueFilter, value); }
        }
        string fStatusCode;
        public string StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<string>(nameof(StatusCode), ref fStatusCode, value); }
        }
        string fStatusMessage;
        [Size(SizeAttribute.Unlimited)]
        public string StatusMessage
        {
            get { return fStatusMessage; }
            set { SetPropertyValue<string>(nameof(StatusMessage), ref fStatusMessage, value); }
        }
        string fWarningCode;
        public string WarningCode
        {
            get { return fWarningCode; }
            set { SetPropertyValue<string>(nameof(WarningCode), ref fWarningCode, value); }
        }
        string fWarningMessage;
        [Size(SizeAttribute.Unlimited)]
        public string WarningMessage
        {
            get { return fWarningMessage; }
            set { SetPropertyValue<string>(nameof(WarningMessage), ref fWarningMessage, value); }
        }
        string fErrorCode;
        public string ErrorCode
        {
            get { return fErrorCode; }
            set { SetPropertyValue<string>(nameof(ErrorCode), ref fErrorCode, value); }
        }
        string fErrorMessage;
        [Size(SizeAttribute.Unlimited)]
        public string ErrorMessage
        {
            get { return fErrorMessage; }
            set { SetPropertyValue<string>(nameof(ErrorMessage), ref fErrorMessage, value); }
        }
    }

}
