//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.LeaveBalanceQueue")]
    public partial class AILeaveBalanceQueue : XPObject
    {
        string fEventCode;
        public string EventCode
        {
            get { return fEventCode; }
            set { SetPropertyValue<string>(nameof(EventCode), ref fEventCode, value); }
        }
        string fEventDescription;
        public string EventDescription
        {
            get { return fEventDescription; }
            set { SetPropertyValue<string>(nameof(EventDescription), ref fEventDescription, value); }
        }
        short fEventSequenceID;
        public short EventSequenceID
        {
            get { return fEventSequenceID; }
            set { SetPropertyValue<short>(nameof(EventSequenceID), ref fEventSequenceID, value); }
        }
        DateTime fEffectiveStartDate;
        public DateTime EffectiveStartDate
        {
            get { return fEffectiveStartDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveStartDate), ref fEffectiveStartDate, value); }
        }
        DateTime fEffectiveEndDate;
        public DateTime EffectiveEndDate
        {
            get { return fEffectiveEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EffectiveEndDate), ref fEffectiveEndDate, value); }
        }
        string fCountryCodeIndicator;
        public string CountryCodeIndicator
        {
            get { return fCountryCodeIndicator; }
            set { SetPropertyValue<string>(nameof(CountryCodeIndicator), ref fCountryCodeIndicator, value); }
        }
        string fEmployeeCode;
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fLeaveTypeCode;
        public string LeaveTypeCode
        {
            get { return fLeaveTypeCode; }
            set { SetPropertyValue<string>(nameof(LeaveTypeCode), ref fLeaveTypeCode, value); }
        }
        string fLeaveCode;
        public string LeaveCode
        {
            get { return fLeaveCode; }
            set { SetPropertyValue<string>(nameof(LeaveCode), ref fLeaveCode, value); }
        }
        decimal fCurrentStartBalance;
        [DbType("decimal(18,4)")]
        public decimal CurrentStartBalance
        {
            get { return fCurrentStartBalance; }
            set { SetPropertyValue<decimal>(nameof(CurrentStartBalance), ref fCurrentStartBalance, value); }
        }
        decimal fCurrentAccrual;
        [DbType("decimal(18,4)")]
        public decimal CurrentAccrual
        {
            get { return fCurrentAccrual; }
            set { SetPropertyValue<decimal>(nameof(CurrentAccrual), ref fCurrentAccrual, value); }
        }
        decimal fCurrentTaken;
        [DbType("decimal(18,4)")]
        public decimal CurrentTaken
        {
            get { return fCurrentTaken; }
            set { SetPropertyValue<decimal>(nameof(CurrentTaken), ref fCurrentTaken, value); }
        }
        decimal fCurrentAdjustment;
        [DbType("decimal(18,4)")]
        public decimal CurrentAdjustment
        {
            get { return fCurrentAdjustment; }
            set { SetPropertyValue<decimal>(nameof(CurrentAdjustment), ref fCurrentAdjustment, value); }
        }
        decimal fCurrentEndBalance;
        [DbType("decimal(18,4)")]
        public decimal CurrentEndBalance
        {
            get { return fCurrentEndBalance; }
            set { SetPropertyValue<decimal>(nameof(CurrentEndBalance), ref fCurrentEndBalance, value); }
        }
        decimal fCurrentPlanned;
        [DbType("decimal(18,4)")]
        public decimal CurrentPlanned
        {
            get { return fCurrentPlanned; }
            set { SetPropertyValue<decimal>(nameof(CurrentPlanned), ref fCurrentPlanned, value); }
        }
        decimal fUnitAdjustment;
        [DbType("decimal(18,4)")]
        public decimal UnitAdjustment
        {
            get { return fUnitAdjustment; }
            set { SetPropertyValue<decimal>(nameof(UnitAdjustment), ref fUnitAdjustment, value); }
        }
        decimal fUnitOverride;
        [DbType("decimal(18,4)")]
        public decimal UnitOverride
        {
            get { return fUnitOverride; }
            set { SetPropertyValue<decimal>(nameof(UnitOverride), ref fUnitOverride, value); }
        }
        decimal fEndBalanceIncludingAdjustment;
        [DbType("decimal(18,4)")]
        public decimal EndBalanceIncludingAdjustment
        {
            get { return fEndBalanceIncludingAdjustment; }
            set { SetPropertyValue<decimal>(nameof(EndBalanceIncludingAdjustment), ref fEndBalanceIncludingAdjustment, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fLastChanged;
        public DateTime LastChanged
        {
            get { return fLastChanged; }
            set { SetPropertyValue<DateTime>(nameof(LastChanged), ref fLastChanged, value); }
        }
        string fQueueComment;
        [Size(SizeAttribute.Unlimited)]
        public string QueueComment
        {
            get { return fQueueComment; }
            set { SetPropertyValue<string>(nameof(QueueComment), ref fQueueComment, value); }
        }
        string fQueueFilter;
        [Size(SizeAttribute.Unlimited)]
        public string QueueFilter
        {
            get { return fQueueFilter; }
            set { SetPropertyValue<string>(nameof(QueueFilter), ref fQueueFilter, value); }
        }
        string fStatusCode;
        public string StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<string>(nameof(StatusCode), ref fStatusCode, value); }
        }
        string fStatusMessage;
        [Size(SizeAttribute.Unlimited)]
        public string StatusMessage
        {
            get { return fStatusMessage; }
            set { SetPropertyValue<string>(nameof(StatusMessage), ref fStatusMessage, value); }
        }
        string fWarningCode;
        public string WarningCode
        {
            get { return fWarningCode; }
            set { SetPropertyValue<string>(nameof(WarningCode), ref fWarningCode, value); }
        }
        string fWarningMessage;
        [Size(SizeAttribute.Unlimited)]
        public string WarningMessage
        {
            get { return fWarningMessage; }
            set { SetPropertyValue<string>(nameof(WarningMessage), ref fWarningMessage, value); }
        }
        string fErrorCode;
        public string ErrorCode
        {
            get { return fErrorCode; }
            set { SetPropertyValue<string>(nameof(ErrorCode), ref fErrorCode, value); }
        }
        string fErrorMessage;
        [Size(SizeAttribute.Unlimited)]
        public string ErrorMessage
        {
            get { return fErrorMessage; }
            set { SetPropertyValue<string>(nameof(ErrorMessage), ref fErrorMessage, value); }
        }
    }

}
