//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace AI.Automation
{

    [Persistent(@"AI.ValidationWarnings")]
    public partial class AIValidationWarnings : XPObject
    {
        DateTime fValidationDate;
        public DateTime ValidationDate
        {
            get { return fValidationDate; }
            set { SetPropertyValue<DateTime>(nameof(ValidationDate), ref fValidationDate, value); }
        }
        string fValidationType;
        [Size(SizeAttribute.Unlimited)]
        public string ValidationType
        {
            get { return fValidationType; }
            set { SetPropertyValue<string>(nameof(ValidationType), ref fValidationType, value); }
        }
        string fValidationMessage;
        [Size(SizeAttribute.Unlimited)]
        public string ValidationMessage
        {
            get { return fValidationMessage; }
            set { SetPropertyValue<string>(nameof(ValidationMessage), ref fValidationMessage, value); }
        }
        string fSourceLocation;
        [Size(SizeAttribute.Unlimited)]
        public string SourceLocation
        {
            get { return fSourceLocation; }
            set { SetPropertyValue<string>(nameof(SourceLocation), ref fSourceLocation, value); }
        }
        string fCountryCode;
        [Size(SizeAttribute.Unlimited)]
        public string CountryCode
        {
            get { return fCountryCode; }
            set { SetPropertyValue<string>(nameof(CountryCode), ref fCountryCode, value); }
        }
        string fEmployeeCode;
        [Size(SizeAttribute.Unlimited)]
        public string EmployeeCode
        {
            get { return fEmployeeCode; }
            set { SetPropertyValue<string>(nameof(EmployeeCode), ref fEmployeeCode, value); }
        }
        string fFieldName;
        [Size(SizeAttribute.Unlimited)]
        public string FieldName
        {
            get { return fFieldName; }
            set { SetPropertyValue<string>(nameof(FieldName), ref fFieldName, value); }
        }
        string fFieldValue;
        [Size(SizeAttribute.Unlimited)]
        public string FieldValue
        {
            get { return fFieldValue; }
            set { SetPropertyValue<string>(nameof(FieldValue), ref fFieldValue, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
